os: windows
language: c

script:
- $msys2 bash -c "cd vice && ./autogen.sh"
- $msys2 bash -c "cd vice && ./configure --disable-arch --disable-pdf-docs || cat config.log"
- $msys2 bash -c "cd vice && make -j -s"
- $msys2 bash -c "cd vice && make bindistzip"
- $msys2 bash -c "cd vice && ls -l"

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## VICE Dependencies
        $msys2 pacman --sync --noconfirm --needed base-devel
        $msys2 pacboy --noconfirm sync zip: subversion:
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-pkg-config
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-gcc
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-ntldd
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-gtk3
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-glew
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-giflib
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-lame
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-libvorbis
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-flac
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-mpg123
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-icoutils
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64