name: Make Release
on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+' # any tag that looks like a release version, ex. v3.6.0
concurrency: 
  group: Release Build
  cancel-in-progress: true

jobs:
  create_release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
  
  # remove_default_release_assets: # the default release assets don't seem to get listed
  #   name: Remove Default Release Assets
  #   runs-on: ubuntu-latest
  #   needs: create_release
  #   steps:
  #     - uses: actions/github-script@v3
  #       with:
  #         github-token: ${{secrets.GITHUB_TOKEN}}
  #         script: |
  #           console.log('GET RELEASE: o: ' + context.repo.owner + ' repo: ' + context.repo.repo + ' rel: ' + '${{ needs.create_release.outputs.release_id }}');
  #           let assets =
  #             (await github.paginate(
  #               github.repos.listReleaseAssets,
  #               {
  #                 owner: context.repo.owner,
  #                 repo: context.repo.repo,
  #                 release_id: '${{ needs.create_release.outputs.release_id }}'
  #               }));
  #           console.log('ASSETS: ' + JSON.stringify(assets));

  #           for (const asset of assets)
  #           {
  #             console.log("Deleting default asset: " + asset.name);
  #             await github.repos.deleteReleaseAsset(
  #               {
  #                 owner: context.repo.owner,
  #                 repo: context.repo.repo,
  #                 asset_id: asset.id
  #               });
  #           }

  #           console.log("Done.");

  build_tarball:
    name: Build Tarball
    needs: create_release
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        run: git config --global core.autocrlf input
      
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get install autoconf automake build-essential byacc flex xa65 dos2unix
          
      - name: Build
        id: build
        shell: bash
        run: |
          cd vice
          ./autogen.sh
          ./configure --with-resid --disable-pdf-docs --enable-headlessui --without-pulse --without-alsa --without-png
          make dist
          echo ::set-output name=tarball_path::$(echo $(pwd)/vice-*.tar.gz)
          echo ::set-output name=tarball_name::$(echo vice-*.tar.gz)

      - name: Upload Artifact Tarball
        uses: actions/upload-artifact@v2
        with:
          name: vice-tarball
          path: ${{ steps.build.outputs.tarball_path }}
          retention-days: 1

      - name: Upload Release Tarball
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.tarball_path }}
          asset_name: ${{ steps.build.outputs.tarball_name }}
          asset_content_type: application/gzip

  build_doc:
    name: Build Headless, Upload Documentation
    needs: build_tarball
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Tarball
        uses: actions/download-artifact@v2
        with:
          name: vice-tarball
      
      - name: Unpack Source
        shell: bash
        run: |
          tar xzvf vice-*.tar.gz
          rm vice-*.tar.gz

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get install autoconf automake build-essential byacc flex xa65 dos2unix
          sudo apt-get install texinfo texlive-fonts-recommended
          
      - name: Build
        id: build
        shell: bash
        run: |
          cd vice-*/
          ./autogen.sh
          ./configure --enable-headlessui --enable-html-docs --without-pulse --without-alsa --without-png
          make -j2
          echo ::set-output name=pdf_path::$(echo $(pwd)/doc/vice.pdf)

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: vice-pdf
          path: ${{ steps.build.outputs.pdf_path }}
          retention-days: 1
  
  build:
    name: Build
    needs: build_doc
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - { msystem: MINGW64, arch: x86_64 }
        - { msystem: MINGW32, arch: i686 }
        ui: [ GTK3, SDL2 ]
    steps:
      - run: git config --global core.autocrlf input
        shell: bash
      
      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Extract Github Actions Build Script
        shell: bash
        run: |
          mv vice/build/msys2/github-actions-build.sh .
          rm -rf vice
      
      - name: Download Documentation
        uses: actions/download-artifact@v2
        with:
          name: vice-pdf

      - name: Download Tarball
        uses: actions/download-artifact@v2
        with:
          name: vice-tarball
      
      - name: Unpack Tarball Source
        shell: bash
        run: |
          tar xzvf vice-*.tar.gz
          rm vice-*.tar.gz
          mv vice-* vice
          mv vice.pdf vice/doc/
          mkdir -p vice/build/msys2/
          mv github-actions-build.sh vice/build/msys2/

      - name: Install GTK3 Dependencies if Applicable
        if: ${{ matrix.ui == 'GTK3' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.arch.msystem }}
          update: true
          install: >-
            git
            base-devel
            mingw-w64-${{ matrix.arch.arch }}-toolchain
            zip
            subversion
            git
            mingw-w64-${{ matrix.arch.arch }}-pkg-config
            mingw-w64-${{ matrix.arch.arch }}-ntldd
            mingw-w64-${{ matrix.arch.arch }}-glew
            mingw-w64-${{ matrix.arch.arch }}-giflib
            mingw-w64-${{ matrix.arch.arch }}-lame
            mingw-w64-${{ matrix.arch.arch }}-libvorbis
            mingw-w64-${{ matrix.arch.arch }}-flac
            mingw-w64-${{ matrix.arch.arch }}-icoutils
            mingw-w64-${{ matrix.arch.arch }}-ffmpeg
            mingw-w64-${{ matrix.arch.arch }}-gtk3
      
      - name: Install SDL2 Dependencies if Applicable
        if: ${{ matrix.ui == 'SDL2' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.arch.msystem }}
          update: true
          install: >-
            git
            base-devel
            mingw-w64-${{ matrix.arch.arch }}-toolchain
            zip
            subversion
            git
            mingw-w64-${{ matrix.arch.arch }}-pkg-config
            mingw-w64-${{ matrix.arch.arch }}-ntldd
            mingw-w64-${{ matrix.arch.arch }}-glew
            mingw-w64-${{ matrix.arch.arch }}-giflib
            mingw-w64-${{ matrix.arch.arch }}-lame
            mingw-w64-${{ matrix.arch.arch }}-libvorbis
            mingw-w64-${{ matrix.arch.arch }}-flac
            mingw-w64-${{ matrix.arch.arch }}-icoutils
            mingw-w64-${{ matrix.arch.arch }}-ffmpeg
            mingw-w64-${{ matrix.arch.arch }}-SDL2
            mingw-w64-${{ matrix.arch.arch }}-SDL2_image

      - name: Build
        id: build
        shell: msys2 {0}
        run: |
          MINGW_INSTALLS=${{ matrix.arch.msystem }} ./vice/build/msys2/github-actions-build.sh ${{ matrix.ui }} ""
          echo ::set-output name=zip_path::$(cygpath -w -a vice/*.zip)
          echo ::set-output name=zip_name::$(basename vice/*.zip)

      - name: Upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build.outputs.zip_path }}
          asset_name: ${{ steps.build.outputs.zip_name }}
          asset_content_type: application/zip
  
  publish_release:
    name: Publish Release
    needs: [create_release, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.repos.updateRelease(
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: ${{ needs.create_release.outputs.release_id }},
                draft: false
              });